### ISSUE TITLE
Plugin not supported on RPI4 / armV7

### ISSUE THREAD

**Issue by mdscientist** [grafana/google-sheets-datasource#103]
Hello,

I'm using Grafana 7.03 armV7 on an RPI4. It seems when I go to test and save the data source with either the API key or JWT file it returns a red box that says Health Check not Implemented (Basically failing to connect to the service). I already whitelisted the domain for the google service and listed the role of (Grafana-Sheet) service as a viewer, so Grafana should not have a problem seeing all the files. After closing and going to the Editor, I typed in the Spreadsheet ID, the drop option is not working for the JWT file, assuming this was caused by not connecting to the service, and I'm getting an "internal server error 500". I know this error has been plaguing some other issues but just wondering if the root cause might be something with the async testDatasource() that "https://grafana.com/tutorials/build-a-data-source-plugin/#5" talks about. 

I don't know much about building a plugin for grafana but I absolutely had my hands slapped by google for calling their API too quickly.

**Comment by ryantxu** [comment]
This plugin currently does not run on arm :(

the warnings and debug is not so clear

**Comment by ckleu** [comment]
Came across this plugin today, but my requirement was also to run on RPI4..

**Comment by simonleventeattila** [comment]
> This plugin currently does not run on arm :(
> 
> the warnings and debug is not so clear

Any chance to support arm / RPI in the future?

**Comment by AuroreVgn** [comment]
I am also interested to have this wonderful plugin working on ARM / RasberryPi 4. Any chance ?

**Comment by PedanticPete** [comment]
It would be great if the plugin told you it wouldn't work on an ARM / Pi4 device, or better yet didn't even let you try it - would have saved me a few hours of pain ... finding this thread was a relief!!  I was getting quite a headache repeatedly hitting my head against my desk!!

Really hope somebody does find the time to implement it, I've done a horrible workaround for the time being, but to just access a google sheet directly would be fantastic.

**Comment by ryantxu** [comment]
^^^ @wbrowne -- this is a good example where better metadata in the plugin manager would be super helpful.
