### ISSUE TITLE
Cells that use formula do not show in Grafana

### ISSUE THREAD

**Issue by adamdewey** [grafana/google-sheets-datasource#139]
I saw that this was fixed in #66, however I'm using v8.1.3 on Ubuntu 20.04 (APT) and still having trouble with this. 

Here is my example sheet: https://docs.google.com/spreadsheets/d/1cIsasPK4bCLus4Pmxb01I-1FiD6jEz4IdtbCT2atZQg/edit#gid=285101922

Am trying to display A1 on sheet 'UpdateDate'

**Comment by zoltanbedi** [comment]
This is the same issue as #123
