### ISSUE TITLE
latest version 1.01 doesnt work in 8.1.0

### ISSUE THREAD

**Issue by evanrich** [grafana/google-sheets-datasource#142]
Tried installing this in 8.1.0, got the following
![image](https://user-images.githubusercontent.com/518320/135357956-1e638d13-e3d2-45c2-866d-724b94e1eed7.png)

Also tried compiling from source and installing that, also didnt work, got a different error though.

**Comment by evanrich** [comment]
UPdate:  the 1.1.0 zip does work (shows plugin success), but when I go to add a panel, it says no sheets found

**Comment by evanrich** [comment]
new error:

``` Error 403: The caller does not have permission, forbidden" refId=A```

**Comment by evanrich** [comment]
Update:  Per this link
https://community.grafana.com/t/google-sheets-datasource-plugi-not-working/27512/12

you need to share the sheet with your service account, then it'll work.  Docs should be updated

**Comment by zoltanbedi** [comment]
I think you sorted out the issues you faced.
