### ISSUE TITLE
chart doesn't display correctly in grafana

### ISSUE THREAD

**Issue by evanrich** [grafana/google-sheets-datasource#143]
I have a spread sheet with dates formatted like 3/1/2019, 4/1/2019, etc.  Here is the table:

![image](https://user-images.githubusercontent.com/518320/135362204-7031a43f-07f9-4d91-b4cc-3aaef98a8e1e.png)

this does not seem to render in grafana correctly, it only pulls the first month, and then all the values:
![image](https://user-images.githubusercontent.com/518320/135362237-b9b8dcdc-05ef-4303-a734-627781f07b2f.png)

MY query config:
![image](https://user-images.githubusercontent.com/518320/135362261-8a72a90a-aa21-4cee-ae7b-941b0da517a9.png)

Am i missing something?

**Comment by zer0kool** [comment]
Hey @evanrich, this is not an issue from the tool. 

Try changing your A1 cell to "DATE" and then B1 to "Dollars".

**Comment by zoltanbedi** [comment]
I'm going to close this issue. Let me know if this is still a problem and we can reopen it.
