### ISSUE TITLE
Support Google default service account.

### ISSUE THREAD

**Issue by gfrankliu** [grafana/google-sheets-datasource#144]
Many other Google data sources (Bigquery, Stackdriver, etc) supports using default service account associated with the instance. Can google-sheets-datasource support that?

**Comment by zoltanbedi** [comment]
Yes, we are working on unifying the authentication methods for the google data sources so we will be able to use service account for authentication. see https://github.com/grafana/grafana/discussions/39907

**Comment by zoltanbedi** [comment]
No, to use the new version you need to have Grafana version 8.1.

**Comment by Eraac** [comment]
It's seems the plugin doesn't allow to use default service account despite the ticket is closed and the work in Grafana is done

Did I miss something to be allowed to use default service account instead of JWT file?

**Comment by zoltanbedi** [comment]
You are right @Eraac this is not added yet. Sorry about it.

**Comment by owenhaynes** [comment]
Yeah this will be great as it will allow for workload identity would be great, which is the recommend practise when working ok GKE
