### ISSUE TITLE
Access Spreadsheets inside a Team Drive

### ISSUE THREAD

**Issue by jonathanabennett** [grafana/google-sheets-datasource#148]
Expected: After following the steps in [this StackOverflow Post](https://stackoverflow.com/questions/43243865/how-to-access-team-drive-using-service-account-with-google-drive-net-api-v3) to add my service account to Team Drive, I expected to see the Spreadsheets in that team drive in the dropdown list.

Result: I do not see the spreadsheets in the team drive on the dropdown list. I only see spreadsheets shared from within someone's My Drive.

**Comment by zer0kool** [comment]
Are you trying to add a spreadsheet into Grafana as a datasource?

**Comment by jonathanabennett** [comment]
I was, yes. But we no longer are using Grafana for what we're trying to do, so I cannot keep working on this.
