### ISSUE TITLE
Query issue

### ISSUE THREAD

**Issue by hjkotze** [grafana/google-sheets-datasource#154]
When I try to use explore and look at the data I get the following error: googleapi: Error 400: API key not valid. Please pass a valid API key. Details: [ { "@type": "type.googleapis.com/google.rpc.ErrorInfo", "domain": "googleapis.com", "metadata": { "service": "sheets.googleapis.com" }, "reason": "API_KEY_INVALID" } ] , badRequest

I used the exact same API key in registering the datasource. I used the test google sheet API key as well as another key that was shared with me. The sheet is not private but public.

I get the error in the Cloud version as well as the self hosted version

Grafana version: 8.4.3
plugin version: 1.1.3

**Comment by zoltanbedi** [comment]
I couldn't reproduce this problem @hjkotze. If you can provide me steps to reproduce this then I'd be able to help.
