### ISSUE TITLE
Issue with incremental data not being loaded

### ISSUE THREAD

**Issue by deolindolucas** [grafana/google-sheets-datasource#197]
Hello,

first of all, thanks for the great plugin,

I've been experiencing an issue which I believe can't be intentional.

I’m using Grafana 8.5.14 with Ubuntu 20 and a Google Spreadsheet datasource plugin, and I need to consume a sheet which is updated regularly, with new data being added as new customers answer an online feedback form.

I’m using the datasource rather simply, configuring it to use JWT auth, and on the dashboard, just inserting my spreadsheet ID and selecting an entire worksheet as my range, and showing this on a Table panel. Easy stuff.

But I noticed that, when new data is inserted on the sheet, my panel isn’t loading this new data. It should be, at least, being updated every 5m, as the Cache option on the datasource implies (I believe it means that every x minutes a new table is loaded from the sheet to the datasource cache, enabling the data not being queried as often).

I tried:

1 - creating a new panel;
2 - creating a new Dashboard;
3 - changing the cache options to lesser intervals, even 0 seconds;
4 - refreshing the dashboard manually instead of using common intervals.
5 - looking at Grafana logs;
6 - searching on the plugin documentation for any mention of this being intentional.

So far the ONLY thing that partially solved the issue was copying the entire sheet and pasting on a new one, and then using this new sheet as a datasource, but new increments still aren’t queried.

Another thing I’ve noticed is, deleted sheets STILL show up on my datasource sheet selector. I wonder if the cache isn’t working properly, or if this plugin is intended for stationary data, but the use case wouldn’t make sense.

I believe it may be a rather inconvenient bug for anyone trying to use it to watch live data.

**Comment by zoltanbedi** [comment]
Hey @deolindolucas,
thanks for opening this issue I'm pretty sure something is not right with the cache. We will take a look at this.

**Comment by zoltanbedi** [comment]
@deolindolucas I tried this out with grafana 10 and setting the cache to 0s worked for me. whenever I refreshed the dashboard I could see the changes. Can you try upgrading your grafana version?

**Comment by zoltanbedi** [comment]
@deolindolucas Let me know if you still seeing this issue and we can reopen it and follow up.
