### ISSUE TITLE
Fix order of rows in table panel

### ISSUE THREAD

**Issue by aknuds1** [grafana/google-sheets-datasource#26]
The ordering of rows gets inverted when visualizing this data source in a table.

I've checked that rows are [inserted](https://github.com/grafana/google-sheets-datasource/blob/86d8affe2e860f78d986aea3cb872ffc1b19c2b8/pkg/googlesheets/googlesheets.go#L147) in the correct order into the data frame, so the bug might lie in the front-end?

**Comment by ryantxu** [comment]
example?  What sheet and what visualization?

React table (or the panel inspector) is the best way to see what we are actually returning

**Comment by aknuds1** [comment]
@ryantxu I'm using [this](https://github.com/grafana/google-sheets-datasource/blob/86d8affe2e860f78d986aea3cb872ffc1b19c2b8/pkg/googlesheets/googlesheets.go#L147) sheet. The visualization is a table (as described above).

**Comment by ryantxu** [comment]
@aknuds1 -- can you check the link above... that is to the source code

**Comment by aknuds1** [comment]
> @aknuds1 -- can you check the link above... that is to the source code

@ryantxu Ah oops, fixed!

**Comment by ryantxu** [comment]
It is an issue that the angular table sorts the results ☹️ 

![image](https://user-images.githubusercontent.com/705951/75793940-f3e07200-5d24-11ea-9f0c-88c45413c5cc.png)

**Comment by aknuds1** [comment]
@ryantxu Thanks for finding the reason for this, I'll check with the front-end squad.

**Comment by torkelo** [comment]
Looks correct to me the table is configured to sort Numbers column in descending order (click column to change or table panel disable sorting, when disabled (ie no caret) the sorting coming from data source should be used)

**Comment by aknuds1** [comment]
Thanks @torkelo, I will double check.
