### ISSUE TITLE
Update the google-sheets-datasource repository 'About' section

### ISSUE THREAD

**Issue by usmangt** [grafana/google-sheets-datasource#281]
Now we finally have the official documentation released after the PR https://github.com/grafana/google-sheets-datasource/pull/255. Please update this repository page to provide more details in the **About** section.

**Description:**
(Current) Load Google Sheets in grafana.
(New suggestion) The Google Sheets data source plugin allows you to visualize Google Spread Sheets data in a Grafana dashboards.

**Website:**
https://grafana.com/grafana/plugins/grafana-googlesheets-datasource/

**Topics:**
grafana, google-sheets-plugin, google-sheets-datasource, grafana-plugins, grafana-datasource

**Comment by gwdawson** [comment]
the information has been updated
