### ISSUE TITLE
Use first row as titles IIF it is all strings

### ISSUE THREAD

**Issue by ryantxu** [grafana/google-sheets-datasource#29]
if the first row has anything other than strings, it should not be used as the column titles

**Comment by zoltanbedi** [comment]
@ryantxu do you remember why we shouldn't do this?

**Comment by ryantxu** [comment]
> why we shouldn't do this?

I think we *should* check that the row is all strings (or empty).  before using them as field names

I have not looked in a while what our current behavior is

**Comment by zoltanbedi** [comment]
I just checked and it worked with a date and a number as well.

**Comment by gabor** [comment]
hi ,considering the info in the issue i will close this for now. if you find that something is missing or not done correctly, please reply and we can reopen the issue.
