### ISSUE TITLE
Security & Google sheets data source 

### ISSUE THREAD

**Issue by torkelo** [grafana/google-sheets-datasource#55]
Just wondering how the security of this data source works. 

How can an admin add this data source limit access to files to a specific folder or files? The Grafana query security model is a bit dangerous with this data source, where even a viewer/datasource can issue any query, and hence access any google docs file (potentially) that the api key can access. 

Depending on how it works now we need to make this 100% clear when setting up the data source. Cannot find any info currently on how the API key is linked to your user file access permissions, just says you need one to access public files, but can you also access private files? 

https://developers.google.com/sheets/api/guides/authorizing#APIKey

**Comment by sunker** [comment]
When using API Key, you'll only be allowed to access public spreadsheets. When API key auth is being used, the datasource won't be able to list all spreadsheets in google drive - you need to add the spreadsheet id manually in the query editor. 

When using a service account (JWT file auth), the spreadsheets that the service account has access to will be listed i a query editor drop down. However, when creating a new service account it will automatically be denied access to all files in the drive account that it's associated with. There are two ways a service account can be granted access to a drive file.
1. Share the document with the email that is associated with the service account
2. Have the admin of the g-suite give root (admin) access to the service account. That way it could access all files within your organization's drive account

I think it's only the second alternative that might raise security concerns. Luckily, this won't be activated by default. 

As you say, this needs to be very clear in the docs! Haven't gotten to that yet unfortunately. :)

**Comment by bergquist** [comment]
I think we should include some details about this in the datasource config page. Like we do for SQL datasources.

![image](https://user-images.githubusercontent.com/618863/76937230-b408b580-68f4-11ea-8b06-7e0f33fdbfa0.png)

Docs could be more explicit.

**Comment by sunker** [comment]
@bergquist @torkelo see  [configuration docs](https://github.com/grafana/google-sheets-datasource/blob/master/src/docs/configuration.md). Is that sufficient?

**Comment by bergquist** [comment]
I think this is good enough. Most people will have to read the docs to set this up.

**Comment by ryantxu** [comment]
I think we are good for now -- lets open a new issue if there are more concerns
