### ISSUE TITLE
Mention sharing service account email on JWT Config page

### ISSUE THREAD

**Issue by sunker** [grafana/google-sheets-datasource#57]
In case Google JWT File auth is being used, and the user has forgotten to enable access to the drive api or the sheets api, the error message is simply `Metric request error`. However, the error message that is returned from the sheets api is something like `Error 403: Google Sheets API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sheets.googleapis.com/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured`. That's a good error message that should be returned to the frontend. 

In case Google JWT File auth is being used, but the service account doesn't have permissions to access a specific spreadsheet, the error message is simply `Metric request error`. The error message that is returned from the sheets api is something like `Error 403: The caller does not have permission, forbidden`. This error message could be improved so that the end user understands that the service account doesn't have permissions to read the given spreadsheet.

**Comment by slim-bean** [comment]
Just to mention here because I found this issue before I found [https://community.grafana.com/t/google-sheets-datasource-plugi-not-working/27512/12](this thread), when using the JWT file and the service account, you also have to share the sheet with the email of the service account for private sheets.

**Comment by zoltanbedi** [comment]
This is already done.
