### ISSUE TITLE
Step-by-step description for configuration

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/google-sheets-datasource#60]
Please, add a step-by-step description for configuration of API keys. 

I've previously created API keys for other services. However, in this case [the documentation](https://github.com/grafana/google-sheets-datasource/blob/master/src/docs/configuration.md) isn't detailed enough to generate the correct keys for it.

Thank you!

**Comment by Zar1416** [comment]
Hello.. i'm using the steps described here and it works.

![image](https://user-images.githubusercontent.com/5398025/77299144-54dbe400-6cec-11ea-827b-e71a2454840a.png)
 Also remember to share your sheet  as indicated in the docs:
_"Sharing
By default, the service account doesn't have access to any spreadsheets within the account/organization that it is associated with. To grant the service account access to files and/or folders in Google Drive, you need to share the file/folder with the service account's email address. The email is specified in the Google JWT File. If you want to know how to share a file or folder, please refer to the official Google drive documentation. "_

**Comment by sunker** [comment]
Yes @sanchomuzax, you can find step-by-step instructions in the config page ui. In depth descriptions about auth types can be found in the  [configuration docs](https://github.com/grafana/google-sheets-datasource/blob/master/src/docs/configuration.md)
