### ISSUE TITLE
Metric request error

### ISSUE THREAD

**Issue by mensa84** [grafana/google-sheets-datasource#63]
Hello,

today I made a fresh installation of Grafana 6.7.1 on Windows 10, installed the Google Sheets datasource plugin 0.9.0 and restarted Grafana.

I created a Google Sheets datasource with my API key.

When I create a new dashbaord -> Add query and enter your example Spreadsheet ID (1TZlZX67Y0s4CvRro_3pCYqRCKuXer81oFp_xcsjPpe8) I immediately get a "Metric request error". 
What I am doing wrong or how can I fix that problem?

See the screenshots:
![Screenshot001065](https://user-images.githubusercontent.com/30125802/77251860-1218fe00-6c51-11ea-8d43-d4a4588a4e43.jpg)

![Screenshot001066](https://user-images.githubusercontent.com/30125802/77251863-1ba26600-6c51-11ea-9608-db714be2855e.jpg)

![Screenshot001067](https://user-images.githubusercontent.com/30125802/77251875-2826be80-6c51-11ea-8fe4-9fb442c144f1.jpg)

![Screenshot001068](https://user-images.githubusercontent.com/30125802/77251878-2eb53600-6c51-11ea-9a60-ed0865dd840a.jpg)

**Comment by baur** [comment]
same error

**Comment by torkelo** [comment]
Yea I also get that error, for me the server logs then say:

googleapi: Error 403: Google Sheets API has not been used in project xxxxxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sheets.googleapis.com/overview?project=xxxxxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

@sunker @aknuds1 any change this error can be returned to the user?

**Comment by sunker** [comment]
yes, this is related to #57 

In case the QueryData function explodes, the error that is returned is not propagated to the frontend. It just returns `Metric request error`. So an update in the SDK is needed

**Comment by sunker** [comment]
@ryantxu, I think this a lot of new users will face this issue. Can we fix this in the next grafana patch release?

**Comment by ryantxu** [comment]
Looking at master on both grafana and this plugin -- when the entity is not found, I see:
![image](https://user-images.githubusercontent.com/705951/77478324-05c0ac80-6ddb-11ea-8947-0fcba0e0cfcf.png)


With a bad api key I get:
![image](https://user-images.githubusercontent.com/705951/77478483-47e9ee00-6ddb-11ea-896d-57767ffe620f.png)


@torkelo -- is this sufficient for now?

**Comment by torkelo** [comment]
Yes

**Comment by mensa84** [comment]
I am new. Can you please explain me what exactly I should do that I could just test with your example Google Sheets file?

**Comment by mensa84** [comment]
I did do exactly what is described here, but it is still not working to access the public test file:

https://docs.google.com/spreadsheets/d/1TZlZX67Y0s4CvRro_3pCYqRCKuXer81oFp_xcsjPpe8/view#gid=0

![Screenshot001072](https://user-images.githubusercontent.com/30125802/77534623-4bdc4580-6e99-11ea-987f-71d2ffa651c2.jpg)

**Comment by mensa84** [comment]
> So if you get this error, it's most likely because you've forgotten to:
> 
>     * enable the api for you project

Can you please tell me, how I could enable the API for my project? For the beginning I just want to test with your public demo file, will I have to enable anything for my project to be able to access that public file?? https://docs.google.com/spreadsheets/d/1TZlZX67Y0s4CvRro_3pCYqRCKuXer81oFp_xcsjPpe8/view#gid=0

>     * you're trying to access a private file, but the file has not been shared with the email account that is associated with your service account

Your public demo file is public, so that could not be the problem.


Did I do anything wrong or is something missing here?
![Screenshot001073](https://user-images.githubusercontent.com/30125802/77633318-915b4a00-6f4f-11ea-954f-edd423522642.jpg)

**Comment by mensa84** [comment]
Nobody can explain how to access the demo Google Sheet, or is this plugin currently just broken?

**Comment by mdkbdg** [comment]
Facing same issue on screen : 
status : 500
statusText : Internal Server Error
message : Metric Request Error

Check on grafana log, these 3 lines are printed when I refresh dashboard : 

> t=2020-03-30T23:09:36+0700 lvl=eror msg="Query failed" logger=plugins.backend pluginId=grafana-googlesheets-datasource error="error while loading timezone: The system cannot find the path specified." refId=A
> 
> t=2020-03-30T23:09:36+0700 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error while loading timezone: The system cannot find the path specified." remote_addr=[::1]
> 
> t=2020-03-30T23:09:36+0700 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_addr=[::1] time_ms=757 size=34 referer="http://localhost:3000/d/YbYj_U9Wz/dashboard-gsheet?orgId=1"

What is `error while loading timezone` supposed to mean?

Further check : 
1. On Grafana, try to change Timezone to Default / Use Browser Timezone / UTC
2. On GoogleAPI, try to not restrict anything, image below
3. On Google Sheet file, try Off, On, and another On, image below
... to no avail, all config above produce same error

![image](https://user-images.githubusercontent.com/31134612/77936936-ca901300-72dd-11ea-8382-6fabe6d3e533.png)

![image](https://user-images.githubusercontent.com/31134612/77937189-2ce91380-72de-11ea-821d-c20d75cdedf2.png)

- I create my own Google Sheet file (exactly the same as the demo)
- using my own API Key (... and yeah I have waited 5 mins like google api says)
- API is activated, and 
- the file is open for public as image above shows.

Grafana v6.7.1 (ca6d08d5cb) on localhost:3000
Plugin Google Sheets v0.9.0

Then, I found this : 
googlesheets.go line 94 inside `getSheetData` function : 

> result, err := client.GetSpreadsheet(qm.Spreadsheet, qm.Range, true)
> 	if err != nil {
> 		return nil, nil, err
> 	}
> 
> 	if result.Properties.TimeZone != "" {
> 		loc, err := time.LoadLocation(result.Properties.TimeZone)
> 		if err != nil {
> 			return nil, nil, fmt.Errorf("error while loading timezone: %w", err)
> 		}
> 		time.Local = loc
> 	}

where should I set the timezone? hmm....

**Comment by daniellee** [comment]
This is the link for the Google Sheets API: https://console.cloud.google.com/apis/library/sheets.googleapis.com

Seems that it needs to enabled for your own GCP even if you are accessing someone elses Google Sheet.

**Comment by mensa84** [comment]
It was already enabled:

![grafik](https://user-images.githubusercontent.com/30125802/78173168-96406200-7457-11ea-9055-19b00a2a2798.png)

**Comment by sunker** [comment]
> > t=2020-03-30T23:09:36+0700 lvl=eror msg="Query failed" logger=plugins.backend pluginId=grafana-googlesheets-datasource error="error while loading timezone: The system cannot find the path specified." refId=A
> > t=2020-03-30T23:09:36+0700 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error while loading timezone: The system cannot find the path specified." remote_addr=[::1]
> > t=2020-03-30T23:09:36+0700 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_addr=[::1] time_ms=757 size=34 referer="http://localhost:3000/d/YbYj_U9Wz/dashboard-gsheet?orgId=1"
> 
> What is `error while loading timezone` supposed to mean?
> 

The timezone does not come from Grafana, it comes from the spreadsheet. See how to change it [here](https://support.google.com/docs/answer/58515?co=GENIE.Platform%3DDesktop&hl=en). Not sure why this happens though - all sheets are supposed to have a default time zone. 

The time zone detection is sort of a nice to have feature, so I don't think we should explode the backend when this error occurs. Created a PR to fix that.

**Comment by daniellee** [comment]
I set up a dashboard that connects to the demo sheet on the [play site](https://play.grafana.org/d/Md-ATqrZk/google-sheets-demo?panelId=2&edit&fullscreen&orgId=1)

**Comment by mensa84** [comment]
I am talking about a local installation, not a hosted one (which the play site is, I think).

**Comment by mensa84** [comment]
@sunker Should there be hidden any solution in your answer? I still don't know what to do to get only simple tests running.

**Comment by mdkbdg** [comment]
On localhost vs play.grafana (am using chrome)

![image](https://user-images.githubusercontent.com/31134612/78248529-fba75800-7516-11ea-98ca-b8e8c0f0be63.png)

**Comment by mensa84** [comment]
Plugin does work on play site does
Plugin does not work on local intallation.

**Comment by shaybrazier** [comment]
I am having the same issue. 

- Local installation.
- drive api enabled.
- sheets api enabled.
- google jwt auth which tests as successful.
- sheet shared with the jwt user email address
- appears to find the spreadsheet (which as been shared with it) when adding query.
- can see api calls recorded in google fnt end.
- receive "Metric request error" in grafana.

Would be grateful for any tips as to what to I am doing wrong.

**Comment by mdkbdg** [comment]
I havent tested it but for local installation, you might wanna try ngrok to expose local grafana installation

**Comment by mensa84** [comment]
Thank you, is there a free version of ngrok?

**Comment by mdkbdg** [comment]
ngrok is free with limitation and quick googling will server many more depending on your platform.
For web-based , try webhook.site

**Comment by moijn001** [comment]
Don't know if it's related, but I repeatedly get this error when trying to load several panels from the same google sheet data source. I'm on Grafana Cloud.

```
Metric request error
Object
status:500
statusText:"Internal Server Error"
data:Object
message:"Metric request error"
config:Object
url:"api/ds/query"
method:"POST"
data:Object
requestId:"Q274"
retry:0
headers:Object
hideFromInspector:false
message:"Metric request error"
```

**Comment by zoltanbedi** [comment]
I'm going to close this issue as this should be resolved now.
