### ISSUE TITLE
 Accessing to sheet with gid

### ISSUE THREAD

**Issue by Zar1416** [grafana/google-sheets-datasource#64]

**Comment by sunker** [comment]
Can you please elaborate @Zar1416?

**Comment by ryantxu** [comment]
reopen if you have more info

**Comment by Zar1416** [comment]
Example for sheet number 2
https://docs.google.com/spreadsheets/d/11xzRJnygBBjJ4u8fZbNcZuPAne-8tjXk_RDFBr3PRek/edit#**gid=579810419** 

gid=579810419

Now  i can acecss only to sheet number 1. Can you add this feature?
![image](https://user-images.githubusercontent.com/5398025/78424894-e2b2ba00-7670-11ea-9a6c-f417230b1b20.png)
