### ISSUE TITLE
Data source access to a specific GID of  sheet 

### ISSUE THREAD

**Issue by Zar1416** [grafana/google-sheets-datasource#75]
Example for sheet number 2
https://docs.google.com/spreadsheets/d/11xzRJnygBBjJ4u8fZbNcZuPAne-8tjXk_RDFBr3PRek/edit#**gid=579810419** 

gid=579810419

Now  i can acecss only to sheet number 1. Can you add this feature?
![image](https://user-images.githubusercontent.com/5398025/78424894-e2b2ba00-7670-11ea-9a6c-f417230b1b20.png)

_Originally posted by @Zar1416 in https://github.com/grafana/google-sheets-datasource/issues/64#issuecomment-609009510_

**Comment by ryantxu** [comment]
Do you know if the API accepts GID?  or is it a concept just in their UI?  if it is in the API we can integrate.... but I have not seen it yet

**Comment by Zar1416** [comment]
I think yes 
![image](https://user-images.githubusercontent.com/5398025/78868692-a651d600-7a43-11ea-9715-aa3422c65cc7.png)
https://developers.google.com/sheets/api/guides/concepts

**Comment by ryantxu** [comment]
Ahh I see -- you know you can do it currenlty using the A1 syntax?  with range: `Foglio2!A:C`

**Comment by zoltanbedi** [comment]
As there was not much interest in this I'll close this. We can reopen it if someone is interested in it.
