### ISSUE TITLE
Expressions feature toggle is not enabled

### ISSUE THREAD

**Issue by rizalsng** [grafana/google-sheets-datasource#76]
I already insert the sheets id and cell data range, but is show "Expressions feature toggle is not enabled" 

any idea ??

<img src="https://user-images.githubusercontent.com/44289286/78503940-15a19e80-7794-11ea-92c7-1b529b0137de.jpg">

**Comment by ryantxu** [comment]
what version of grafana are you running?  this will only work with 6.7+

**Comment by ferrellw** [comment]
I too had this problem and was running on 6.6.1. Once I updated to 6.7.2 everything worked flawlessly.
