### ISSUE TITLE
Use variable in Query

### ISSUE THREAD

**Issue by mukin123** [grafana/google-sheets-datasource#82]
I have a case where I would like to use variable in Query.
For example to use it in the Range. When I select variable (let's say $range) from dropdown on the top of the dashboard to change the Query Range:
![изображение](https://user-images.githubusercontent.com/63838256/79538718-8d71a200-808d-11ea-8d86-408912a1741b.png)
This would be helpful to make dynamic tables or charts, whit different sheets or ranges.

Same would be helpful also for Spreadsheet ID.

**Comment by ryantxu** [comment]
Should be included in the latest release (only works with 7.beta)  holler if you have any issues with it

**Comment by mukin123** [comment]
Thanks a lot, I appreciate!
