### ISSUE TITLE
Can we also have filtering feature?

### ISSUE THREAD

**Issue by karankural** [grafana/google-sheets-datasource#85]
Example:
My spreadsheet can have a column "status" with multiple values "open", "closed" and "in-progress". I should be able to apply a where clause to show only "open" status items.

**Comment by mukin123** [comment]
That would be good to have. Right now you can filter only on time.
You have some limited functions in "Datatable Panel Plugin" - to sort column (asc/desc) to use common Search filter.
Here is my implementation if Gsheet in this panel:
![изображение](https://user-images.githubusercontent.com/63838256/79737624-417c6280-8304-11ea-97ba-675980a77338.png)

**Comment by ryantxu** [comment]
This will get a lot more interesting in grafana 7.0 -- we are adding the concept of a "transformation" in the frontend that will let you further process results from the datasource.

**Comment by mukin123** [comment]
@ryantxu , I am counting the days for this release! I was waiting for this Mathematics between metrics :)

**Comment by zoltanbedi** [comment]
This is not possible with the API, by now you can do this in grafana with transformations.
