### ISSUE TITLE
XHR error

### ISSUE THREAD

**Issue by 7yl4r** [grafana/google-sheets-datasource#96]
When I try selecting this plugin in the "add data source" page I get the following error:

```
Plugin Error
(SystemJS) XHR error (404 Not Found) loading http://grafana:3000/public/react?bust=1589029128830 Error loading http://grafana:3000/public/react as "react" from http://grafana:3000/public/plugins/grafana-googlesheets-datasource/module.js
```

system details:
```
[root@grafana ~]# grafana-cli --version
Grafana cli version 4.4.3

[root@grafana ~]# head -n1 /etc/*elease
==> /etc/centos-release <==
CentOS Linux release 7.3.1611 (Core) 
```

**Comment by ryantxu** [comment]
Interesting... are you running Grafana 4?  This plugin in targeting 7+ so you may need to upgrade

(there is one release that will work on 6.7)

**Comment by ryantxu** [comment]
I'll close assuming you are not running 7+, but if you are please reopen and let me know
