### ISSUE TITLE
Select multiple columns which are not side by side

### ISSUE THREAD

**Issue by julianofischer** [grafana/google-sheets-datasource#98]
Is there a way to select columns like below?
='Sheet1'!B2:B151;'Sheet1'!D2:D151

**Comment by ryantxu** [comment]
sounds good -- Given their APIs, this is either better to do as two queries that you join, or as one query that gets every thing and ignores the "skipped columns" IE:
```
= Sheet1!B2:D151
```
drop column C

**Comment by JeremyDomper** [comment]
Have the same problem

**Comment by abedhossainn** [comment]
anyone found any solution for this?

**Comment by zoltanbedi** [comment]
This is not supported @abedhossainn

**Comment by zoltanbedi** [comment]
I'm going to close this feature request. The preferred way is to have multiple queries.

**Comment by OrenLalehzari** [comment]
why not support this style Sheet1!A1:A32,C1:C32? how multiple queries is the preferred way ..
